#! /bin/sh

PLASMA_HOME=`echo $0 | sed -e "s/\/[^\/]*$//"`
PLASMA_BIN=$PLASMA_HOME

PBM=`mktemp`
PJF=`mktemp`

anytopnm $1 | ppmtopgm | pgmtopbm -threshold >$PBM

ocrad -x - $PBM | $PLASMA_BIN/orf2pjf >$PJF

$PLASMA_BIN/coldplasma --in $PBM \
    --lib $PLASMA_HOME/charlibs/cyr1.lib \
    --pjf $PJF \
    | iconv -f utf8 | sed -f $PLASMA_HOME/charlibs/cyr.sed

rm -f $PJF $PBM
